# Default values for my-app chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

backend:
  name: backend
  image:
    repository: europe-west1-docker.pkg.dev/infomineo/infominerva/backend
    pullPolicy: Always
    tag: 
  service:
    type: ClusterIP
    port: 8000
    targetPort: 8000

frontend:
  name: frontend
  image:
    repository: europe-west1-docker.pkg.dev/infomineo/infominerva/frontend
    pullPolicy: Always
    tag: 
  service:
    type: ClusterIP
    port: 80
    targetPort: 3000

ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts:
    - host: infominerva.infomineo.com # <-- TODO: Change this
      paths:
        - path: /
          pathType: ImplementationSpecific
          service:
            name: frontend
            port: 80
        - path: /api
          pathType: ImplementationSpecific
          service:
            name: backend
            port: 8000
  tls: []

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

# New section for managing secrets
# For production, these sensitive values should ideally be managed outside of version control
# (e.g., using Helm --set, separate values files, or a secrets management tool like Vault).
secrets:
  create: true # Set to true to create the Kubernetes Secret resources

  backend:
    nameSuffix: "backend-secrets"
    data:
      DATABASE_URL: "postgresql://infomineo:slimano@127.0.0.1:5432/Infominerva"
      POSTGRES_USER: "infomineo"
      POSTGRES_PASSWORD: "slimano"
      POSTGRES_DB: "Infominerva"

  frontend:
    nameSuffix: "frontend-secrets"
    data:
      REACT_APP_URL: "http://34.44.235.46/:8000/"

serviceAccount:
  create: false
  annotations: {}
  name: ""
