{{- if .Values.secrets.create }}
---
# Backend Secrets
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "infominerva.fullname" . }}-{{ .Values.secrets.backend.nameSuffix }}
  labels:
    {{- include "infominerva.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
type: Opaque
data:
  {{- range $key, $value := .Values.secrets.backend.data }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
---
# Frontend Secrets
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "infominerva.fullname" . }}-{{ .Values.secrets.frontend.nameSuffix }}
  labels:
    {{- include "infominerva.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
type: Opaque
data:
  {{- range $key, $value := .Values.secrets.frontend.data }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }}
